In [44]:
import math
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd

In [45]:
class Node:
    def __init__(self, node_id, owner, cyborgs, production):
        self.node_id = node_id
        self.owner = owner
        self.cyborgs = cyborgs
        self.production = production

    def __str__(self):
        return str(self.node_id) + ' ' + str(self.owner) + ' ' + str(self.cyborgs) + ' ' + str(self.production)


class Edge:
    def __init__(self, node1, node2, distance):
        self.node1 = node1
        self.node2 = node2
        self.distance = distance
    
    def __str__(self):
        return str(self.node1) + ' ' + str(self.node2) + ' ' + str(self.distance)

class Graph:
    def __init__(self, l_nodes_infos=[], l_edges=[]):
        self.nodes = []
        self.edges = []
        for node in l_nodes_infos:
            self.add_node(Node(node[0], node[1], node[2], node[3]))
        for edge in l_edges:
            self.add_edge(Edge(edge[0], edge[1], edge[2]))

    def add_node(self, node):
        self.nodes.append(node)

    def add_edge(self, edge):
        self.edges.append(edge)

    def getEdge(self, node1, node2):
        for edge in self.edges:
            if node1 in [edge.node1, edge.node2] and node2 in [edge.node1, edge.node2]:
                return edge

In [46]:
l_nodes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
l_nodes_infos = [[0, 0, 0, 0], [1, 1, 25, 3], [2, -1, 25, 3], [3, 0, 7, 3], [4, 0, 7, 3], [5, 0, 5, 1], [6, 0, 5, 1], [7, 0, 5, 1], [8, 0, 5, 1], [9, 0, 3, 1], [10, 0, 3, 1], [11, 0, 0, 0], [12, 0, 0, 0], [13, 0, 6, 3], [14, 0, 6, 3]]
l_edges = [[0, 1, 6], [0, 2, 6], [0, 3, 3], [0, 4, 3], [0, 5, 4], [0, 6, 4], [0, 7, 3], [0, 8, 3], [0, 9, 7], [0, 10, 7], [0, 11, 1], [0, 12, 1], [0, 13, 4], [0, 14, 4], [1, 2, 14], [1, 3, 5], [1, 4, 10], [1, 5, 3], [1, 6, 11], [1, 7, 3], [1, 8, 10], [1, 9, 1], [1, 10, 15], [1, 11, 4], [1, 12, 9], [1, 13, 1], [1, 14, 12], [2, 3, 10], [2, 4, 5], [2, 5, 11], [2, 6, 3], [2, 7, 10], [2, 8, 3], [2, 9, 15], [2, 10, 1], [2, 11, 9], [2, 12, 4], [2, 13, 12], [2, 14, 1], [3, 4, 8], [3, 5, 1], [3, 6, 8], [3, 7, 5], [3, 8, 5], [3, 9, 4], [3, 10, 11], [3, 11, 2], [3, 12, 5], [3, 13, 5], [3, 14, 7], [4, 5, 8], [4, 6, 1], [4, 7, 5], [4, 8, 5], [4, 9, 11], [4, 10, 4], [4, 11, 5], [4, 12, 2], [4, 13, 7], [4, 14, 5], [5, 6, 9], [5, 7, 3], [5, 8, 7], [5, 9, 2], [5, 10, 12], [5, 11, 1], [5, 12, 6], [5, 13, 2], [5, 14, 9], [6, 7, 7], [6, 8, 3], [6, 9, 12], [6, 10, 2], [6, 11, 6], [6, 12, 1], [6, 13, 9], [6, 14, 2], [7, 8, 7], [7, 9, 5], [7, 10, 10], [7, 11, 2], [7, 12, 5], [7, 13, 1], [7, 14, 9], [8, 9, 10], [8, 10, 5], [8, 11, 5], [8, 12, 2], [8, 13, 9], [8, 14, 1], [9, 10, 15], [9, 11, 5], [9, 12, 9], [9, 13, 3], [9, 14, 12], [10, 11, 9], [10, 12, 5], [10, 13, 12], [10, 14, 3], [11, 12, 3], [11, 13, 3], [11, 14, 6], [12, 13, 6], [12, 14, 3], [13, 14, 10]]
l_troop = []

In [57]:
n_nodes, n_edges = (15, 105)
l_nodes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
l_nodes_infos = [[0, 0, 0, 0], [1, 1, 3, 3], [2, -1, 3, 3], [3, 0, 7, 3], [4, 0, 7, 3], [5, 0, 5, 1], [6, 0, 5, 1], [7, 0, 5, 1], [8, 0, 5, 1], [9, 0, 3, 1], [10, 0, 3, 1], [11, 0, 0, 0], [12, 0, 0, 0], [13, 0, 6, 3], [14, 0, 6, 3]]
l_edges = [[0, 1, 6], [0, 2, 6], [0, 3, 3], [0, 4, 3], [0, 5, 4], [0, 6, 4], [0, 7, 3], [0, 8, 3], [0, 9, 7], [0, 10, 7], [0, 11, 1], [0, 12, 1], [0, 13, 4], [0, 14, 4], [1, 2, 14], [1, 3, 5], [1, 4, 10], [1, 5, 3], [1, 6, 11], [1, 7, 3], [1, 8, 10], [1, 9, 1], [1, 10, 15], [1, 11, 4], [1, 12, 9], [1, 13, 1], [1, 14, 12], [2, 3, 10], [2, 4, 5], [2, 5, 11], [2, 6, 3], [2, 7, 10], [2, 8, 3], [2, 9, 15], [2, 10, 1], [2, 11, 9], [2, 12, 4], [2, 13, 12], [2, 14, 1], [3, 4, 8], [3, 5, 1], [3, 6, 8], [3, 7, 5], [3, 8, 5], [3, 9, 4], [3, 10, 11], [3, 11, 2], [3, 12, 5], [3, 13, 5], [3, 14, 7], [4, 5, 8], [4, 6, 1], [4, 7, 5], [4, 8, 5], [4, 9, 11], [4, 10, 4], [4, 11, 5], [4, 12, 2], [4, 13, 7], [4, 14, 5], [5, 6, 9], [5, 7, 3], [5, 8, 7], [5, 9, 2], [5, 10, 12], [5, 11, 1], [5, 12, 6], [5, 13, 2], [5, 14, 9], [6, 7, 7], [6, 8, 3], [6, 9, 12], [6, 10, 2], [6, 11, 6], [6, 12, 1], [6, 13, 9], [6, 14, 2], [7, 8, 7], [7, 9, 5], [7, 10, 10], [7, 11, 2], [7, 12, 5], [7, 13, 1], [7, 14, 9], [8, 9, 10], [8, 10, 5], [8, 11, 5], [8, 12, 2], [8, 13, 9], [8, 14, 1], [9, 10, 15], [9, 11, 5], [9, 12, 9], [9, 13, 3], [9, 14, 12], [10, 11, 9], [10, 12, 5], [10, 13, 12], [10, 14, 3], [11, 12, 3], [11, 13, 3], [11, 14, 6], [12, 13, 6], [12, 14, 3], [13, 14, 10]]
l_troop = [[15, 1, 1, 13, 7, 1], [16, 1, 1, 9, 4, 1], [17, 1, 1, 5, 6, 3], [18, 1, 1, 7, 6, 3], [19, 1, 1, 3, 1, 5], [20, 1, 1, 4, 1, 10], [27, -1, 2, 10, 4, 1], [28, -1, 2, 6, 6, 3], [29, -1, 2, 8, 6, 3], [30, -1, 2, 14, 7, 1], [31, -1, 2, 4, 2, 5], [26, -1, 2, -1, -1, 0]]

In [86]:
n_nodes, n_edges = (9, 36)
l_nodes = [0, 1, 2, 3, 4, 5, 6, 7, 8]
l_nodes_infos = [[0, 0, 0, 0], [1, 1, 0, 0], [2, -1, 0, 0], [3, 0, 0, 0], [4, 0, 0, 0], [5, 1, 4, 3], [6, 0, 11, 3], [7, 1, 3, 2], [8, -1, 4, 2]]
l_edges = [[0, 1, 2], [0, 2, 2], [0, 3, 5], [0, 4, 5], [0, 5, 6], [0, 6, 6], [0, 7, 2], [0, 8, 2], [1, 2, 5], [1, 3, 2], [1, 4, 9], [1, 5, 2], [1, 6, 9], [1, 7, 1], [1, 8, 5], [2, 3, 9], [2, 4, 2], [2, 5, 9], [2, 6, 2], [2, 7, 5], [2, 8, 1], [3, 4, 12], [3, 5, 1], [3, 6, 12], [3, 7, 3], [3, 8, 9], [4, 5, 12], [4, 6, 1], [4, 7, 9], [4, 8, 3], [5, 6, 13], [5, 7, 5], [5, 8, 8], [6, 7, 8], [6, 8, 5], [7, 8, 6]]
l_troop = [[13, -1, 8, 6, 14, 1], [14, 1, 7, 8, 2, 3], [15, -1, 8, 1, 2, 2], [16, 1, 5, 8, 3, 6], [17, 1, 7, 8, 2, 4], [18, -1, 8, 1, 2, 3], [19, 1, 5, 8, 3, 7], [20, 1, 7, 8, 2, 5], [21, -1, 8, 1, 2, 4], [22, 1, 5, 8, 3, 8], [23, 1, 7, 8, 2, 6], [24, -1, 8, -1, -1, 0]]
troops_to_my_nodes = [[15, -1, 8, 1, 2, 2], [18, -1, 8, 1, 2, 3], [21, -1, 8, 1, 2, 4]]

In [87]:
graph = Graph(l_nodes_infos, l_edges)

In [88]:
all_nodes = [[node.node_id, node.owner, node.cyborgs, node.production] for node in graph.nodes]
pd.DataFrame(all_nodes, columns=['node_id', 'owner', 'cyborgs', 'production'])

   node_id  owner  cyborgs  production
0        0      0        0           0
1        1      1        0           0
2        2     -1        0           0
3        3      0        0           0
4        4      0        0           0
5        5      1        4           3
6        6      0       11           3
7        7      1        3           2
8        8     -1        4           2

In [95]:
t_my_nodes = sorted([[node.node_id, node.owner, node.cyborgs, node.production] for node in graph.nodes if node.owner == 1], key=lambda x: -x[2])
df_my_nodes = pd.DataFrame(t_my_nodes, columns=['node_id', 'owner', 'cyborgs', 'production'])
df_my_nodes

   node_id  owner  cyborgs  production
0        5      1        4           3
1        7      1        3           2
2        1      1        0           0

In [96]:
pd.DataFrame(l_troop, columns=['id','owner','node_dep','node_cib','cyborgs','distance'])

    id  owner  node_dep  node_cib  cyborgs  distance
0   13     -1         8         6       14         1
1   14      1         7         8        2         3
2   15     -1         8         1        2         2
3   16      1         5         8        3         6
4   17      1         7         8        2         4
5   18     -1         8         1        2         3
6   19      1         5         8        3         7
7   20      1         7         8        2         5
8   21     -1         8         1        2         4
9   22      1         5         8        3         8
10  23      1         7         8        2         6
11  24     -1         8        -1       -1         0

In [99]:
troops_to_my_nodes = sorted([t for t in l_troop if t[1] == -1 and t[3] != -1 and graph.nodes[t[3]].owner == 1], key=lambda t: -t[4])
pd.DataFrame(troops_to_my_nodes, columns=['id','owner','node_dep','node_cib','cyborgs','distance'])

   id  owner  node_dep  node_cib  cyborgs  distance
0  15     -1         8         1        2         2
1  18     -1         8         1        2         3
2  21     -1         8         1        2         4

In [107]:
for troop in troops_to_my_nodes[0:1]:
    node_cib = troop[3]
    my_closets_nodes_from_node_cib = sorted([node for node in graph.nodes if node.owner == 1], key=lambda x: (x.cyborgs, graph.getEdge(x.node_id, node_cib).distance), reverse=True)
    print( 'MOVE ' + str(my_closets_nodes_from_node_cib[0].node_id) + ' ' + str(node_cib) + ' ' + str(troop[4]))

MOVE 5 1